"""remove_difficulty_column

Revision ID: e9ffa9bdccb6
Revises: 5c925586cfbd
Create Date: 2025-12-14 13:20:21.267349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9ffa9bdccb6'
down_revision: Union[str, None] = '5c925586cfbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizzes', 'difficulty')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('difficulty', sa.VARCHAR(), server_default=sa.text("'medium'::character varying"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
